name: CI CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v2
        with:
            toolchain: nightly
            components: clippy
            override: true
      - name: rust-clippy-check
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          tokne: ${{secrets.GITHUB_TOKEN}}
          args: --locked --all-targets --all-features --workspace

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run Tests
      run: make test
